[package]
name = "ocularity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.29.0"
tiny_http = "0.12"
url = "2.4.1"
url-escape = "0.1.1"
png = "0.17.10"